name: AirCore
main: com.ftxeven.aircore.AirCore
version: 1.2.0
api-version: "1.21"
author: ftxeven
description: Core commands and features for all servers.
load: STARTUP
softdepend: [PlaceholderAPI, LuckPerms, Vault]
folia-supported: true

commands:
  aircore:
    description: Main plugin command.
    usage: /aircore <reload|version>
    permission: aircore.command.admin
  msg:
    description: Sends a private message to a player.
    usage: /msg <player> <message>
    permission: aircore.command.msg
  reply:
    description: Replies to the last private message.
    usage: /reply <message>
    permission: aircore.command.reply
  msgtoggle:
    description: Toggles private messages on or off.
    usage: /msgtoggle [player]
    permission: aircore.command.msgtoggle
  mentiontoggle:
    description: Toggles mention notifications.
    usage: /mentiontoggle [player]
    permission: aircore.command.mentiontoggle
  socialspy:
    description: Toggles Social Spy on or off.
    usage: /socialspy [player]
    permission: aircore.command.socialspy
  chattoggle:
    description: Toggles global chat visibility.
    usage: /chattoggle [player]
    permission: aircore.command.chattoggle
  eco:
    description: Economy administration command.
    usage: /eco <give|take|set|reset> <player> [amount]
    permission: aircore.command.eco
  pay:
    description: Send money to another player.
    usage: /pay <player> <amount>
    permission: aircore.command.pay
  paytoggle:
    description: Toggles whether you can receive payments.
    usage: /paytoggle [player]
    permission: aircore.command.paytoggle
  balance:
    description: Check your current balance.
    usage: /balance [player]
    permission: aircore.command.balance
  sell:
    description: Sell items.
    usage: /sell
    permission: aircore.command.sell
  tpa:
    description: Sends a teleport request to a player.
    usage: /tpa <player>
    permission: aircore.command.tpa
  tpahere:
    description: Sends a teleport-here request to a player.
    usage: /tpahere <player>
    permission: aircore.command.tpahere
  tpaccept:
    description: Accepts a player's teleport request.
    usage: /tpaccept [player]
    permission: aircore.command.tpaccept
  tpdeny:
    description: Declines a player's teleport request.
    usage: /tpdeny [player]
    permission: aircore.command.tpdeny
  tptoggle:
    description: Toggles whether you can receive teleport requests.
    usage: /tptoggle [player]
    permission: aircore.command.tptoggle
  tp:
    description: Teleports to a player.
    usage: /tp <player> [player]
    permission: aircore.command.tp
  tphere:
    description: Teleports a player to your location.
    usage: /tphere <player>
    permission: aircore.command.tphere
  tppos:
    description: Teleports to a specific location.
    usage: /tppos <x> <y> <z>
    permission: aircore.command.tppos
  tpoffline:
    description: Teleports to a player's last location.
    usage: /tpoffline <player>
    permission: aircore.command.tpoffline
  sethome:
    description: Set a home at your current location.
    usage: /sethome <homename>
    permission: aircore.command.sethome
  delhome:
    description: Delete one of your homes.
    usage: /delhome <homename>
    permission: aircore.command.delhome
  home:
    description: Teleports to your home.
    usage: /home <homename>
    permission: aircore.command.home
  kit:
    description: Claim a kit.
    usage: /kit <kitname>
    permission: aircore.command.kit
  createkit:
    description: Create a new kit from your inventory.
    usage: /createkit <kitname> [parameters] [cooldown]
    permission: aircore.command.createkit
  delkit:
    description: Delete a kit.
    usage: /delkit <kitname>
    permission: aircore.command.delkit
  editkit:
    description: Edit a kit.
    usage: /editkit <kitname> [parameters] [cooldown]
    permission: aircore.command.editkit
  spawn:
    description: Teleport to spawn.
    usage: /spawn
    permission: aircore.command.spawn
  setspawn:
    description: Set a spawn.
    usage: /setspawn
    permission: aircore.command.setspawn
  warp:
    description: Teleport to a warp.
    usage: /warp <warpname>
    permission: aircore.command.warp
  setwarp:
    description: Set a warp.
    usage: /setwarp <warpname>
    permission: aircore.command.setwarp
  delwarp:
    description: Delete a warp.
    usage: /delwarp <warpname>
    permission: aircore.command.delwarp
  block:
    description: Blocks a player from interacting with you.
    usage: /block <player>
    permission: aircore.command.block
  unblock:
    description: Removes a player from your block list.
    usage: /unblock <player>
    permission: aircore.command.unblock
  clearinventory:
    description: Clears inventory.
    usage: /clearinventory [player]
    permission: aircore.command.clearinventory
  feed:
    description: Feed yourself or other players.
    usage: /feed [player]
    permission: aircore.command.feed
  heal:
    description: Heal yourself or other players.
    usage: /heal [player]
    permission: aircore.command.heal
  time:
    description: Set the time.
    usage: /time <set|add> <time> [world]
    permission: aircore.command.time
  weather:
    description: Change the weather.
    usage: /weather <sun|rain|thunder> [world]
    permission: aircore.command.weather
  craftingtable:
    description: Opens a virtual crafting table.
    usage: /craftingtable
    permission: aircore.command.craftingtable
  anvil:
    description: Opens a virtual anvil.
    usage: /anvil
    permission: aircore.command.anvil
  cartography:
    description: Opens a virtual cartography table.
    usage: /cartography
    permission: aircore.command.cartography
  loom:
    description: Opens a virtual loom.
    usage: /loom
    permission: aircore.command.loom
  smithingtable:
    description: Opens a virtual smithing table.
    usage: /smithingtable
    permission: aircore.command.smithingtable
  stonecutter:
    description: Opens a virtual stonecutter.
    usage: /stonecutter
    permission: aircore.command.stonecutter
  grindstone:
    description: Opens a virtual grindstone.
    usage: /grindstone
    permission: aircore.command.grindstone
  enderchest:
    description: Opens an ender chest.
    usage: /enderchest [player]
    permission: aircore.command.enderchest
  gamemode:
    description: Change gamemode.
    usage: /gamemode <mode> [player]
    permission: aircore.command.gamemode
  invsee:
    description: View other player's inventory.
    usage: /invsee <player>
    permission: aircore.command.invsee
  kill:
    description: Kill yourself or other players.
    usage: /kill [player]
    permission: aircore.command.kill
  afk:
    description: Toggle AFK status.
    usage: /afk
    permission: aircore.command.afk
  god:
    description: Toggles god mode.
    usage: /god [player]
    permission: aircore.command.god
  speed:
    description: Set walk/fly speed.
    usage: /speed [walking/flying] <speed> [player]
    permission: aircore.command.speed
  fly:
    description: Toggles fly.
    usage: /fly [player]
    permission: aircore.command.fly
  repair:
    description: Repair an item.
    usage: /repair
    permission: aircore.command.repair
  give:
    description: Give an item.
    usage: /give <item> [amount] [player]
    permission: aircore.command.give
  back:
    description: Teleport to the last death location.
    usage: /back
    permission: aircore.command.back
  announcement:
    description: Manage and trigger custom announcements.
    usage: /announcements <reload|trigger|toggle>
    permission: aircore.command.announcement
  announcetoggle:
    description: Toggles whether you see periodic announcements.
    usage: /announcetoggle
    permission: aircore.command.announcetoggle
  pweather:
    description: Changes the weather for a player.
    usage: /pweather <type> [world] [player]
    permission: aircore.command.pweather
  ptime:
    description: Changes the time for a player.
    usage: /ptime <set|add> <time> [world] [player]
    permission: aircore.command.ptime

permissions:
  aircore.command.admin: {description: "Admin command.", default: op}
  aircore.command.msg: {description: "Use /msg.", default: op}
  aircore.command.msg.all: {description: "Msg everyone.", default: op}
  aircore.command.reply: {description: "Use /reply.", default: op}
  aircore.command.msgtoggle: {description: "Toggle PMs.", default: op}
  aircore.command.msgtoggle.others: {description: "Toggle PMs for others.", default: op}
  aircore.command.mentiontoggle: {description: "Toggle mentions.", default: op}
  aircore.command.mentiontoggle.others: {description: "Toggle mentions for others.", default: op}
  aircore.command.socialspy: {description: "Toggle Social Spy.", default: op}
  aircore.command.socialspy.others: {description: "Toggle Social Spy for others.", default: op}
  aircore.command.chattoggle: {description: "Toggle chat.", default: op}
  aircore.command.chattoggle.others: {description: "Toggle chat for others.", default: op}
  aircore.chat.link: {description: "Clickable links.", default: op}
  aircore.chat.display.*: {description: "All display tags.", default: op}
  aircore.chat.mention: {description: "Mention players.", default: op}
  aircore.chat.color.*:
    description: All color tags.
    default: op
    children:
      aircore.chat.color.black: true
      aircore.chat.color.dark_blue: true
      aircore.chat.color.dark_green: true
      aircore.chat.color.dark_aqua: true
      aircore.chat.color.dark_red: true
      aircore.chat.color.dark_purple: true
      aircore.chat.color.gold: true
      aircore.chat.color.gray: true
      aircore.chat.color.dark_gray: true
      aircore.chat.color.blue: true
      aircore.chat.color.green: true
      aircore.chat.color.aqua: true
      aircore.chat.color.red: true
      aircore.chat.color.light_purple: true
      aircore.chat.color.yellow: true
      aircore.chat.color.white: true
      aircore.chat.color.hex: true
  aircore.chat.format.*:
    description: All format tags.
    default: op
    children:
      aircore.chat.format.bold: true
      aircore.chat.format.italic: true
      aircore.chat.format.underlined: true
      aircore.chat.format.strikethrough: true
      aircore.chat.format.obfuscated: true
      aircore.chat.format.rainbow: true
  aircore.command.eco: {description: "Use /eco.", default: op}
  aircore.command.eco.*:
    description: All eco subcommands.
    default: op
    children:
      aircore.command.eco: true
      aircore.command.eco.give: true
      aircore.command.eco.give.all: true
      aircore.command.eco.give.server: true
      aircore.command.eco.take: true
      aircore.command.eco.take.all: true
      aircore.command.eco.take.server: true
      aircore.command.eco.set: true
      aircore.command.eco.set.all: true
      aircore.command.eco.set.server: true
      aircore.command.eco.reset: true
      aircore.command.eco.reset.all: true
      aircore.command.eco.reset.server: true
  aircore.command.pay: {description: "Use /pay.", default: op}
  aircore.command.paytoggle: {description: "Toggle payments.", default: op}
  aircore.command.paytoggle.others: {description: "Toggle payments for others.", default: op}
  aircore.command.balance: {description: "Check balance.", default: op}
  aircore.command.balance.others: {description: "Check others' balance.", default: op}
  aircore.command.tpa: {description: "Use /tpa.", default: op}
  aircore.command.tpahere: {description: "Use /tpahere.", default: op}
  aircore.command.tpahere.all: {description: "Use /tpahere @a", default: op}
  aircore.command.tpaccept: {description: "Use /tpaccept.", default: op}
  aircore.command.tpaccept.all: {description: "Accept all.", default: op}
  aircore.command.tpdeny: {description: "Use /tpdeny.", default: op}
  aircore.command.tpdeny.all: {description: "Deny all.", default: op}
  aircore.command.tptoggle: {description: "Toggle TP.", default: op}
  aircore.command.tptoggle.others: {description: "Toggle TP for others.", default: op}
  aircore.command.tp: {description: "Use /tp.", default: op}
  aircore.command.tphere: {description: "Use /tphere.", default: op}
  aircore.command.tphere.all: {description: "Use /tphere @a", default: op}
  aircore.command.tp.others: {description: "TP players to others.", default: op}
  aircore.command.tppos: {description: "Use /tppos.", default: op}
  aircore.command.tpoffline: {description: "Use /tpoffline.", default: op}
  aircore.command.sethome: {description: "Use /sethome.", default: op}
  aircore.command.delhome: {description: "Use /delhome.", default: op}
  aircore.command.delhome.others: {description: "Del others' home.", default: op}
  aircore.command.home: {description: "Use /home.", default: op}
  aircore.command.home.others: {description: "Visit others' home.", default: op}
  aircore.command.kit: {description: "Use /kit.", default: op}
  aircore.command.kit.*: {description: "All kits.", default: op}
  aircore.command.createkit: {description: "Use /createkit.", default: op}
  aircore.command.delkit: {description: "Use /delkit.", default: op}
  aircore.command.editkit: {description: "Use /editkit.", default: op}
  aircore.command.block: {description: "Block player.", default: op}
  aircore.command.unblock: {description: "Unblock player.", default: op}
  aircore.command.spawn: {description: "Use /spawn.", default: op}
  aircore.command.setspawn: {description: "Use /setspawn.", default: op}
  aircore.command.setwarp: {description: "Use /setwarp.", default: op}
  aircore.command.delwarp: {description: "Use /delwarp.", default: op}
  aircore.command.warp: {description: "Use /warp.", default: op}
  aircore.command.warp.*: {description: "All warps.", default: op}
  aircore.command.clearinventory: {description: "Use /clearinventory.", default: op}
  aircore.command.clearinventory.others: {description: "Clear others' inv.", default: op}
  aircore.command.clearinventory.all: {description: "Clear all inv.", default: op}
  aircore.command.feed: {description: "Use /feed.", default: op}
  aircore.command.feed.others: {description: "Feed others.", default: op}
  aircore.command.feed.all: {description: "Feed all.", default: op}
  aircore.command.heal: {description: "Use /heal.", default: op}
  aircore.command.heal.others: {description: "Heal others.", default: op}
  aircore.command.heal.all: {description: "Heal all.", default: op}
  aircore.command.time: {description: "Use /time.", default: op}
  aircore.command.weather: {description: "Use /weather.", default: op}
  aircore.command.pweather: {description: "Use /pweather.", default: op}
  aircore.command.pweather.others: {description: "Set others' /pweather.", default: op}
  aircore.command.ptime: { description: "Use /ptime.", default: op }
  aircore.command.ptime.others: { description: "Set others' /ptime.", default: op }
  aircore.command.virtual.*:
    description: Access to all virtual workstations.
    default: op
    children:
      aircore.command.virtual.craftingtable: true
      aircore.command.virtual.anvil: true
      aircore.command.virtual.cartography: true
      aircore.command.virtual.loom: true
      aircore.command.virtual.smithingtable: true
      aircore.command.virtual.stonecutter: true
      aircore.command.virtual.grindstone: true
  aircore.command.enderchest: {description: "Open enderchest.", default: op}
  aircore.command.enderchest.others: {description: "Open others' ec.", default: op}
  aircore.command.enderchest.others.modify: {description: "Modify others' ec.", default: op}
  aircore.command.gamemode: {description: "Set gamemode.", default: op}
  aircore.command.gamemode.others: {description: "Set others' gamemode.", default: op}
  aircore.command.invsee: {description: "Use /invsee.", default: op}
  aircore.command.invsee.modify: {description: "Modify invsee.", default: op}
  aircore.command.kill: {description: "Use /kill.", default: op}
  aircore.command.kill.others: {description: "Kill others.", default: op}
  aircore.command.kill.all: {description: "Kill all.", default: op}
  aircore.command.afk: {description: "Use /afk.", default: op}
  aircore.command.afk.notify: {description: "AFK alerts.", default: op}
  aircore.command.god: {description: "Use /god.", default: op}
  aircore.command.god.others: {description: "God for others.", default: op}
  aircore.command.speed: {description: "Use /speed.", default: op}
  aircore.command.speed.others: {description: "Speed for others.", default: op}
  aircore.command.fly: {description: "Use /fly.", default: op}
  aircore.command.fly.others: {description: "Fly for others.", default: op}
  aircore.command.repair: {description: "Use /repair.", default: op}
  aircore.command.repair.all: {description: "Repair all.", default: op}
  aircore.command.give: {description: "Use /give.", default: op}
  aircore.command.give.others: {description: "Give to others.", default: op}
  aircore.command.give.all: {description: "Give to all.", default: op}
  aircore.command.back: {description: "Use /back.", default: op}
  aircore.command.sell: {description: "Use /sell.", default: op}
  aircore.bypass.chat.cooldown: {description: "No chat CD.", default: op}
  aircore.bypass.chat.toggle: {description: "Bypass PM toggles.", default: op}
  aircore.bypass.command.*: {description: "Bypass all CMD cooldowns.", default: op}
  aircore.bypass.block: {description: "Bypass blocks.", default: op}
  aircore.bypass.pay.toggle: {description: "Bypass pay toggle.", default: op}
  aircore.bypass.teleport.toggle: {description: "Bypass TP toggle.", default: op}
  aircore.bypass.teleport.countdown: {description: "No TP warm-up.", default: op}
  aircore.bypass.block.limit.*: {description: "No block limit.", default: op}
  aircore.bypass.home.limit.*: {description: "No home limit.", default: op}
  aircore.bypass.home.worlds: {description: "Homes everywhere.", default: op}
  aircore.bypass.kit.cooldown: {description: "No kit CD.", default: op}
  aircore.bypass.kit.onetime: {description: "Unlimited 1-time kits.", default: op}
  aircore.command.announcement: { description: "Use /announcements.", default: op }
  aircore.command.announcetoggle: { description: "Use /announcetoggle.", default: op }
  aircore.command.announcetoggle.others: { description: "Toggle others' announcements.", default: op }
